
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyanbuiztwezaozvbndh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YW5idWl6dHdlemFvenZibmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzgyNTMsImV4cCI6MjA1ODA1NDI1M30.kJEVWCUFA3CW-MCN9Gc0VioO2tSrP9q16m7OnFUJ_Ak";

// Enable realtime subscriptions for tables
const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Enable realtime for specific tables
// Initialize the realtime subscription for tables
const channel = supabase.channel('schema-db-changes');

// Subscribe to changes on the products table
channel.on('postgres_changes', { 
  event: '*', 
  schema: 'public', 
  table: 'products' 
}, () => {
  console.log('Products table updated');
});

// Subscribe to changes on the sales table
channel.on('postgres_changes', { 
  event: '*', 
  schema: 'public', 
  table: 'sales' 
}, () => {
  console.log('Sales table updated');
});

// Subscribe to changes on the sale_items table
channel.on('postgres_changes', { 
  event: '*', 
  schema: 'public', 
  table: 'sale_items' 
}, () => {
  console.log('Sale items table updated');
});

// Start the subscription
channel.subscribe((status) => {
  console.log('Realtime subscription status:', status);
});

export { supabase };
