
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyanbuiztwezaozvbndh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YW5idWl6dHdlemFvenZibmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzgyNTMsImV4cCI6MjA1ODA1NDI1M30.kJEVWCUFA3CW-MCN9Gc0VioO2tSrP9q16m7OnFUJ_Ak";

// Enable realtime subscriptions for tables
const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Enable realtime for specific tables
supabase.channel('schema-db-changes')
  .on('postgres_changes', { 
    event: '*', 
    schema: 'public', 
    table: 'products' 
  }, () => {})
  .on('postgres_changes', { 
    event: '*', 
    schema: 'public', 
    table: 'customers' 
  }, () => {})
  .on('postgres_changes', { 
    event: '*', 
    schema: 'public', 
    table: 'sales' 
  }, () => {})
  .on('postgres_changes', { 
    event: '*', 
    schema: 'public', 
    table: 'sale_items' 
  }, () => {})
  .subscribe();

export { supabase };
